### ISSUE TITLE
Package subpath './is-truthy' is not defined by "exports"

### ISSUE THREAD

**Issue by a7medpa** [netlify-templates/gatsby-ecommerce-theme#91]
After cloning and running 'npm i', I did npm start and I got the following error

> gatsby-ecommerce-theme@1.0.0 start
> gatsby develop -p 5000

internal/modules/cjs/loader.js:491
  throw new ERR_PACKAGE_PATH_NOT_EXPORTED(basePath, mappingKey);
  ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './is-truthy' is not defined by "exports" in /Applications/gatsby-ecommerce-theme/node_modules/gatsby-core-utils/package.json
    at applyExports (internal/modules/cjs/loader.js:491:9)
    at resolveExports (internal/modules/cjs/loader.js:507:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:635:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Applications/gatsby-ecommerce-theme/node_modules/gatsby-cli/lib/reporter/reporter.js:34:17)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

When running gatsby build
/usr/local/lib/node_modules/gatsby-cli/lib/reporter/reporter.js:41
let isVerbose = (0, _isTruthy.isTruthy)(process.env.GATSBY_REPORTER_ISVERBOSE);
                ^

ReferenceError: _isTruthy is not defined
    at Object.<anonymous> (/usr/local/lib/node_modules/gatsby-cli/lib/reporter/reporter.js:41:17)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/gatsby-cli/lib/reporter/catch-exit-signals.js:16:17)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)

**Comment by a7medpa** [comment]
My node version was on v12, upgrading to the latest one and running `npm install -g gatsby-cli `fixed my issue
